In [3]:
from sklearn import linear_model
import pandas as pd
import numpy as np


In [1]:
X, y = [[1],[2.1],[3]], [[1],[2],[3]]

1. Fit a LinearRegression model from Scikit-learn with X the features and y the target and predict for `x_pred = [[4]]`

In [10]:
reg = linear_model.LinearRegression()
reg.fit(X=X, y=y)
reg.predict([[4]])

array([[3.96013289]])

2. Print the coefficients (`coefs_`) and the intercept (`intercept_`), the score (`score`) of the regression of X and y.

In [12]:
reg.coef_

array([[0.99667774]])

In [13]:
reg.intercept_

array([-0.02657807])

In [15]:
reg.score(X,y)

0.9966777408637874